-- Autogenerated by Luapress v3.5.2
-- For available configuation options, see: luapress.org
-- Or see the default config at:
-- github.com/Fizzadar/Luapress/blob/develop/luapress/default_config.lua

local config = {
    title = 'jordanmajd.com',
    template = 'jordanmajd',
    url = 'http://localhost:8000',
    index_page = 'home',
    force_index_page = true,
    envs = {
      production = {
        url = 'https://jordanmajd.com'
      }
    }
}

return config
